"""empty message

Revision ID: 50624bbfc22f
Revises: 4d923c26958c
Create Date: 2020-04-28 17:34:28.841652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50624bbfc22f'
down_revision = '4d923c26958c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.drop_column('roles', 'pass_secure')
    # ### end Alembic commands ###
